[package]
name = "swell"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.14.0"
log = "0.4.21"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
